### ISSUE TITLE
Voice acting and text

### ISSUE THREAD

**Issue by DemonSpirit** [mitunayon/rewindgame2018#23]

**Comment by DemonSpirit** [comment]
UPDATE waiting for the actress
https://www.fiverr.com/kim_reiko?source=gig-cards&ref_ctx_id=2be685ae-6b0c-4bc4-90f2-9e2eb4e7d32e

**Comment by mitunayon** [comment]
Voice Recordings have been cut and edited in commit 17185331ebe95c801e06dd3e5f0bbaa80f82a7da
